import { ReactQueryClientProvider } from "@/provider";
import { NavigationBar } from "@/widgets";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-[#f5f5f3]`}
        suppressHydrationWarning={true}
      >
        <ReactQueryClientProvider>
          <ReactQueryDevtools initialIsOpen={false} />
          <NavigationBar />
          {children}
        </ReactQueryClientProvider>
      </body>
    </html>
  );
}
